services:
  vc:
    build: vc
    container_name: vc_service
    ports:
      - "8000:8000"
    depends_on:
      - vc_db
    environment:
      DATABASE_URL: ${DATABASE_URL_VC}

    volumes:
      - "./vc/alembic/versions:/app/alembic/versions"
    restart: unless-stopped

  ac:
    build: ac
    container_name: ac_service
    ports:
      - "8001:8000"
    depends_on:
      - ac_db
    environment:
      DATABASE_URL: ${DATABASE_URL_AC}
      ADMIN_API_KEY:  ${ADMIN_API_KEY}

    volumes:
      - "./ac/alembic/versions:/app/alembic/versions"
    restart: unless-stopped

  ac_db:
    image: postgres:16
    container_name: ac_postgres
    environment:
      POSTGRES_DB: vds
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - pgdata_ac:/var/lib/postgresql/data
    restart: unless-stopped

  vc_db:
    image: postgres:16
    container_name: vc_postgres
    environment:
      POSTGRES_DB: vds
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - pgdata_vc:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata_ac:
  pgdata_vc:
